### PR TITLE
Display username on login success

### PR DESCRIPTION
**Pull request by weihesdlegend**
## Description
Most changes are reformatting. Please focus on the real changes.

## Root Cause
When users log in, they should see their usernames.

## Solution
login page passes username to the index page

### CODE REVIEW

**Comment by sananand007** [comment]
looks good. 

Could you make it the `same` color as `About` on the Left-hand corner?

**Review by sananand007 — APPROVED** [review]

**Review by sananand007 — CHANGES_REQUESTED** [review]
as discussed seems this still needs changes

**Comment by weihesdlegend** [comment]
> looks good.
> 
> Could you make it the `same` color as `About` on the Left-hand corner?

The About is a link, and currently we don't have user profile, so this will be just a `span` tag for text content.

**Review by sananand007 — APPROVED** [review]
lg

**Pull request merged**
