### PR TITLE
Fix: Set only JWT in session cookies

### PR DESCRIPTION
**Pull request by weihesdlegend**
## Description
Previously, after users logged in, the backend server assigns both JWT and a username to the session cookies. The username cookie is redundant and confusing to the front-end as well as backend functions. In this change, we attempt to remove the username from the cookie assignments and extract the username from the JWT claims.

## Solution
* Use `jwt-decode` module to extract claims on the front-end
* Simplify backend user authentication methods

### CODE REVIEW

**Review by rwangsc18 — APPROVED** [review]
Approve.
I still need more time to fully understand the changes. But the idea to use JWT instead of session cookies to extract information is clear to me.

**Comment by sananand007** [comment]
I am still looking at it @weihesdlegend

**Comment by weihesdlegend** [comment]
> I am still looking at it @weihesdlegend 

Sure, feel free to comment away. Also see the deployment if you want test it.

**Review by sananand007 — APPROVED** [review]
lg.. very nice funtionality

**Pull request merged**
